/**
 * Tree-shakeable registry of all error codes in the system.
 * Use `ErrorCode.SOME_CODE` in code and the `ErrorCode` type for signatures.
 */
export const ErrorCode = {
  // Generic
  NOT_FOUND: 'NOT_FOUND',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  CONFLICT: 'CONFLICT',
  UNPROCESSABLE_ENTITY: 'UNPROCESSABLE_ENTITY',
  DUPLICATE_ENTRY: 'DUPLICATE_ENTRY',
  RECORD_NOT_FOUND: 'RECORD_NOT_FOUND',

  // Auth
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_EMAIL_EXISTS: 'AUTH_EMAIL_EXISTS',
  AUTH_INVALID_PASSWORD: 'AUTH_INVALID_PASSWORD',
  AUTH_ACCOUNT_SUSPENDED: 'AUTH_ACCOUNT_SUSPENDED',
  AUTH_INVALID_REFRESH_TOKEN: 'AUTH_INVALID_REFRESH_TOKEN',
  AUTH_INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',
  AUTH_OAUTH_FAILED: 'AUTH_OAUTH_FAILED',
  AUTH_RESET_TOKEN_INVALID: 'AUTH_RESET_TOKEN_INVALID',

  // Validation
  VAL_INVALID_INPUT: 'VAL_INVALID_INPUT',
  VAL_INVALID_DATE_RANGE: 'VAL_INVALID_DATE_RANGE',
  VAL_INVALID_UUID: 'VAL_INVALID_UUID',
  VAL_INVALID_EMAIL: 'VAL_INVALID_EMAIL',
  VAL_MISSING_REQUIRED_FIELD: 'VAL_MISSING_REQUIRED_FIELD',
  VAL_STRING_TOO_LONG: 'VAL_STRING_TOO_LONG',
  VAL_INVALID_ENUM_VALUE: 'VAL_INVALID_ENUM_VALUE',
  VAL_NEGATIVE_NUMBER: 'VAL_NEGATIVE_NUMBER',
  VAL_FUTURE_DATE_REQUIRED: 'VAL_FUTURE_DATE_REQUIRED',
  VAL_INVALID_COORDINATES: 'VAL_INVALID_COORDINATES',

  // Rate Limit
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',

  // User
  USR_NOT_FOUND: 'USR_NOT_FOUND',
  USR_PROFILE_INCOMPLETE: 'USR_PROFILE_INCOMPLETE',
  USR_ALREADY_VERIFIED: 'USR_ALREADY_VERIFIED',

  // Trip
  TRIP_NOT_FOUND: 'TRIP_NOT_FOUND',
  TRIP_INACTIVE: 'TRIP_INACTIVE',
  TRIP_NO_AVAILABILITY: 'TRIP_NO_AVAILABILITY',

  // Place
  PLACE_NOT_FOUND: 'PLACE_NOT_FOUND',
  PLACE_INACTIVE: 'PLACE_INACTIVE',

  // Hotel
  HTL_NOT_FOUND: 'HTL_NOT_FOUND',
  HTL_ROOM_NOT_FOUND: 'HTL_ROOM_NOT_FOUND',
  HTL_NO_AVAILABILITY: 'HTL_NO_AVAILABILITY',
  HTL_EXCEEDS_OCCUPANCY: 'HTL_EXCEEDS_OCCUPANCY',

  // Guide
  GDE_NOT_FOUND: 'GDE_NOT_FOUND',
  GDE_UNAVAILABLE: 'GDE_UNAVAILABLE',
  GDE_SUSPENDED: 'GDE_SUSPENDED',
  GDE_INACTIVE: 'GDE_INACTIVE',

  // Transportation
  TRNS_VEHICLE_NOT_FOUND: 'TRNS_VEHICLE_NOT_FOUND',
  TRNS_UNAVAILABLE: 'TRNS_UNAVAILABLE',

  // Booking
  BKNG_NOT_FOUND: 'BKNG_NOT_FOUND',
  BKNG_UNAVAILABLE: 'BKNG_UNAVAILABLE',
  BKNG_INVALID_DATE_RANGE: 'BKNG_INVALID_DATE_RANGE',
  BKNG_CONFIRMED_CANNOT_MODIFY: 'BKNG_CONFIRMED_CANNOT_MODIFY',
  BKNG_NON_REFUNDABLE_WINDOW: 'BKNG_NON_REFUNDABLE_WINDOW',
  BKNG_NOT_AUTHOR: 'BKNG_NOT_AUTHOR',
  BKNG_ALREADY_CANCELLED: 'BKNG_ALREADY_CANCELLED',
  BKNG_EXPIRED: 'BKNG_EXPIRED',
  BKNG_PAYMENT_PENDING: 'BKNG_PAYMENT_PENDING',
  BKNG_EXCEEDS_OCCUPANCY: 'BKNG_EXCEEDS_OCCUPANCY',

  // Payment
  PAY_INTENT_FAILED: 'PAY_INTENT_FAILED',
  PAY_NOT_FOUND: 'PAY_NOT_FOUND',
  PAY_ALREADY_REFUNDED: 'PAY_ALREADY_REFUNDED',
  PAY_NON_REFUNDABLE: 'PAY_NON_REFUNDABLE',
  PAY_STRIPE_ERROR: 'PAY_STRIPE_ERROR',
  PAY_WEBHOOK_INVALID: 'PAY_WEBHOOK_INVALID',
  PAY_WEBHOOK_DUPLICATE: 'PAY_WEBHOOK_DUPLICATE',
  PAY_AMOUNT_MISMATCH: 'PAY_AMOUNT_MISMATCH',
  PAY_METHOD_NOT_SUPPORTED: 'PAY_METHOD_NOT_SUPPORTED',
  PAY_QR_EXPIRED: 'PAY_QR_EXPIRED',

  // Review
  REV_NOT_FOUND: 'REV_NOT_FOUND',
  REV_NOT_AUTHOR: 'REV_NOT_AUTHOR',
  REV_NO_COMPLETED_BOOKING: 'REV_NO_COMPLETED_BOOKING',
  REV_EDIT_WINDOW_EXPIRED: 'REV_EDIT_WINDOW_EXPIRED',
  REV_ALREADY_EXISTS: 'REV_ALREADY_EXISTS',
  REV_INVALID_RATING: 'REV_INVALID_RATING',

  // Favorite
  FAVORITE_NOT_FOUND: 'FAVORITE_NOT_FOUND',
  FAVORITES_LIMIT_EXCEEDED: 'FAVORITES_LIMIT_EXCEEDED',
  FAVORITE_ALREADY_EXISTS: 'FAVORITE_ALREADY_EXISTS',

  // Search
  SRCH_QUERY_TOO_SHORT: 'SRCH_QUERY_TOO_SHORT',
  SRCH_QUERY_TOO_LONG: 'SRCH_QUERY_TOO_LONG',

  // Student Verification
  STD_VERIFICATION_NOT_FOUND: 'STD_VERIFICATION_NOT_FOUND',
  STD_ALREADY_VERIFIED: 'STD_ALREADY_VERIFIED',
  STD_VERIFICATION_PENDING: 'STD_VERIFICATION_PENDING',
  STD_DOCUMENT_REQUIRED: 'STD_DOCUMENT_REQUIRED',

  // Loyalty
  LYL_INSUFFICIENT_POINTS: 'LYL_INSUFFICIENT_POINTS',
  LYL_INVALID_REDEMPTION: 'LYL_INVALID_REDEMPTION',
  LYL_TRANSACTION_NOT_FOUND: 'LYL_TRANSACTION_NOT_FOUND',

  // Emergency
  EMRG_ALERT_NOT_FOUND: 'EMRG_ALERT_NOT_FOUND',
  EMRG_ALERT_ALREADY_RESOLVED: 'EMRG_ALERT_ALREADY_RESOLVED',
  EMRG_LOCATION_SHARE_NOT_FOUND: 'EMRG_LOCATION_SHARE_NOT_FOUND',
  EMRG_LOCATION_SHARE_EXPIRED: 'EMRG_LOCATION_SHARE_EXPIRED',
  EMRG_LOCATION_SHARE_REVOKED: 'EMRG_LOCATION_SHARE_REVOKED',

  // Discount Code
  DSC_NOT_FOUND: 'DSC_NOT_FOUND',
  DSC_EXPIRED: 'DSC_EXPIRED',
  DSC_USAGE_LIMIT_REACHED: 'DSC_USAGE_LIMIT_REACHED',
  DSC_MIN_VALUE_NOT_MET: 'DSC_MIN_VALUE_NOT_MET',

  // AI
  AI_INVALID_SERVICE_KEY: 'AI_INVALID_SERVICE_KEY',
  AI_SERVICE_UNAVAILABLE: 'AI_SERVICE_UNAVAILABLE',
  AI_TIMEOUT: 'AI_TIMEOUT',
  AI_INVALID_CONTEXT: 'AI_INVALID_CONTEXT',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
