'use client'

import { useEffect } from 'react'

/**
 * Registers the PWA service worker generated by Serwist (public/sw.js).
 * (Requirements 12.2, 12.5 — offline support via service worker.)
 *
 * The service worker is only emitted by production builds, so registration is
 * skipped in development to avoid stale-cache issues while iterating.
 */
export function ServiceWorkerRegister() {
  useEffect(() => {
    if (
      process.env.NODE_ENV !== 'production' ||
      typeof window === 'undefined' ||
      !('serviceWorker' in navigator)
    ) {
      return
    }

    const register = () => {
      navigator.serviceWorker.register('/sw.js').catch((error) => {
        // Registration failure is non-fatal; the app works without offline support.
        console.error('Service worker registration failed', error)
      })
    }

    // Defer registration until the page has loaded to avoid contending with
    // critical resource fetching.
    if (document.readyState === 'complete') {
      register()
    } else {
      window.addEventListener('load', register)
      return () => window.removeEventListener('load', register)
    }
  }, [])

  return null
}
