/**
 * Stable, machine-readable error codes returned in the response envelope.
 * Clients branch on these, never on human-readable messages.
 */
export enum ErrorCode {
  // Generic
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  NOT_FOUND = 'NOT_FOUND',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  CONFLICT = 'CONFLICT',
  RATE_LIMITED = 'RATE_LIMITED',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  BAD_REQUEST = 'BAD_REQUEST',

  // Auth
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_EMAIL_TAKEN = 'AUTH_EMAIL_TAKEN',
  AUTH_REFRESH_INVALID = 'AUTH_REFRESH_INVALID',
  AUTH_REFRESH_REUSED = 'AUTH_REFRESH_REUSED',

  // Catalog / availability
  CATALOG_UNKNOWN_REFERENCE = 'CATALOG_UNKNOWN_REFERENCE',
  AVAILABILITY_UNAVAILABLE = 'AVAILABILITY_UNAVAILABLE',

  // Drafts / bookings / payments
  DRAFT_INVALID_MUTATION = 'DRAFT_INVALID_MUTATION',
  BOOKING_HOLD_EXPIRED = 'BOOKING_HOLD_EXPIRED',
  BOOKING_INVALID_STATE = 'BOOKING_INVALID_STATE',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  PAYMENT_SIGNATURE_INVALID = 'PAYMENT_SIGNATURE_INVALID',

  // Storage (R2 / object images)
  STORAGE_UNAVAILABLE = 'STORAGE_UNAVAILABLE',

  // Vibe / AI
  AI_UNAVAILABLE = 'AI_UNAVAILABLE',
  AI_TOOL_FAILED = 'AI_TOOL_FAILED',
  AI_RATE_LIMITED = 'AI_RATE_LIMITED',
}
